import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import SideBar from "@/components/sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Side Nav-bar",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex dark:bg-black dark:text-white">
          {/* This side bar will always be fixed */}
          <SideBar />
          {/* These are the pages */}
          <div className="mt-10 ml-20">{children}</div>
        </div>
      </body>
    </html>
  );
}
